export const DRAW_CARD = 'DRAW_CARD'
export const FOCUS_CARD = 'FOCUS_CARD'
export const PICK_CARD = 'PICK_CARD'
export const UNPICK_CARD = 'UNPICK_CARD'
export const MOVE_CARD = 'MOVE_CARD'
export const RESET_ROTATION = 'RESET_ROTATION'
export const MOVE_FAKE_CARD = 'MOVE_FAKE_CARD'
export const PUT_CARD = 'PUT_CARD'
export const SET_DECK_POSITION = 'SET_DECK_POSITION'
export const PICK_PAWN = 'PICK_PAWN'
export const FOCUS_PAWN = 'FOCUS_PAWN'
export const ATTACK_START = 'ATTACK_START'
export const ATTACK_CANCEL = 'ATTACK_CANCEL'
export const ATTACK = 'ATTACK'
export const ATTACKS_END = 'ATTACKS_END'

export const WINDOW_RESIZE = 'WINDOW_RESIZE'
